### ISSUE TITLE
docs: Add example for specifying multiple V8 arguments to node

### ISSUE THREAD

**Issue by alexdulin** [ammarm08/quasimodo#12]
I initially tried to pass options like this:
```js
['--turbo --max_inlined_source_size=700']
```

which is, in hindsight, clearly wrong. Including in the examples something with two arguments like this would prevent fools like myself from making the same mistake:
```js
['--turbo', '--max_inlined_source_size=700']
```

**Comment by ammarm08** [comment]
Good idea, updated readme to show this
